In [3]:
cimport numpy as np #importing numpy library
vec=np.arange(1,21,dtype=float) #creating a numpy vector with arange function
print(vec)
vec=vec.reshape(4,5)#reshaping the vector with reshape() function
print(vec)
vec=np.where(np.isin(vec,vec.max(axis=1)),0,vec)#finding the max values in row and replacing them with zero using np.where() and np.max() function
veclass Employee:#Employee class
    empCount=0 ##employeeConut is used to keep track of numner of employee objects
    salSum=0 #salSum is used to take the average of the salaries of the Employee object 
    def __init__(self,name,family,salary,department): #constructor for Employee as per the reuirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1
        Employee.salSum+=self.salary
    def avg(self):
        return Employee.salSum/Employee.empCount
    def displayCount(self): #One of the functions in Employee class
        print ("Total Employee %d" % Employee.empCount)
    def displayEmployee(self):#another function for employee class
        print("Name : ", self.name, "Family: ", self.family , "Salary: ", self.salary, "department:",self.department)

emp1 = Employee("suma","lawrance",2000,"software")#Employee objects creation with intialization
emp2 = Employee("janu","john",5000,"fatbee")
print("avg:",emp2.avg())#calling average function
class FulltimeEmployee(Employee):#FulltimeEmployee class with Employee as its parent class
    def __init__(self,name,family,salary,department,c_name):#constructor for FulltimeEmployee
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setCompany(self,c_name):#one of the FulltimeEmployee class function
        self.c_name=c_name
    def getCompany(self):
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
Deepthi=FulltimeEmployee("Deepthi","Pulipati",50000,"Front-end","TCS")#FultimeEmployee object
Deepthi.setCompany("Meta")#calling the member functions of FulltimeEmploye and Employee
Deepthi.getCompany(),Deepthi.displayEmployee(),emp1.displayCount()

avg: 3500.0
Name :  Deepthi Family:  Pulipati Salary:  50000 department: Front-end
Total Employee 3


('Meta', None, None)

In [9]:
import numpy as np

# Create a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 10, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print("Random Vector:")
print(random_vector)

print("\nReshaped Array:")
print(reshaped_array)


Random Vector:
[3.09041024 5.79905735 2.59385421 0.         8.84432165 4.07778765
 0.         6.1527051  3.81118371 7.39302544 6.1106543  7.15664245
 0.         3.09072152 2.16878359 8.93724414 5.31508349 6.86988879
 0.         4.2882637 ]

Reshaped Array:
[[3.09041024 5.79905735 2.59385421 0.         8.84432165]
 [4.07778765 0.         6.1527051  3.81118371 7.39302544]
 [6.1106543  7.15664245 0.         3.09072152 2.16878359]
 [8.93724414 5.31508349 6.86988879 0.         4.2882637 ]]
