In [17]:
class Employee:#Employee class
    empCount=0 ##employeeConut is used to keep track of numner of employee objects
    salSum=0 #salSum is used to take the average of the salaries of the Employee object 
    def __init__(self,name,family,salary,department): #constructor for Employee as per the requirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1
        Employee.salSum+=self.salary
    def avg(self):
        return Employee.salSum/Employee.empCount
    def displayCount(self): #One of the functions in Employee class
        print ("Total Employee %d" % Employee.empCount)
    def displayEmployee(self):#another function for employee class
        print("Name : ", self.name, "Family: ", self.family , "Salary: ", self.salary, "department:",self.department)

emp1 = Employee("suma","latha",2000,"software")#Employee objects creation with intialization
emp2 = Employee("anil","babu",5000,"starbucks")
print("avg:",emp2.avg())#calling average function
class FulltimeEmployee(Employee):#FulltimeEmployee class with Employee as its parent class
    def __init__(self,name,family,salary,department,c_name):#constructor for FulltimeEmployee
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setCompany(self,c_name):#one of the FulltimeEmployee class function
        self.c_name=c_name
    def getCompany(self):
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
Deepthi=FulltimeEmployee("Deepthi","pulipati",100000,"Front-end","TCS")#FultimeEmployee object
Deepthi.setCompany("Meta")#calling the member functions of FulltimeEmploye and Employee
Deepthi.getCompany(),Deepthi.displayEmployee(),emp1.displayCount()

avg: 3500.0
Name :  Deepthi Family:  pulipati Salary:  100000 department: Front-end
Total Employee 3


('Meta', None, None)

In [12]:
import numpy as np

# Create a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 15, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print("Random Vector:")
print(random_vector)

print("\nReshaped Array:")
print(reshaped_array)


Random Vector:
[ 0.         10.48898423  2.48016434  1.70943333  2.04131632 12.99920273
  9.35890728 13.15893858 13.40029222  0.          1.83771897  5.27286187
  9.28055458  0.          3.84237384 10.49061884  7.3257957   0.
  1.54654612 11.87440142]

Reshaped Array:
[[ 0.         10.48898423  2.48016434  1.70943333  2.04131632]
 [12.99920273  9.35890728 13.15893858 13.40029222  0.        ]
 [ 1.83771897  5.27286187  9.28055458  0.          3.84237384]
 [10.49061884  7.3257957   0.          1.54654612 11.87440142]]
